"""
Bake the hand-cursor shape from tools/mouse-hand-cursor-icon.svg into a C# data file
(src/WormsCursor.Core/HandShape.cs) and render a preview.

The SVG is line-art (double-contour strokes + knuckle marks). For a SOLID, opaque
cursor we render it as:
  1. fill the outer silhouette with the FILL colour (opaque body), then
  2. fill the FULL line-art (all contours, even-odd) with the OUTLINE colour on top.
That reproduces the original drawing — outline + finger-separation lines + knuckle
marks — but with a filled interior instead of a see-through one. Filling (rather than
stroking a dense polyline) keeps the rounded parts artifact-free.

Coordinates are emitted translated so the index fingertip (the cursor hotspot) sits at
the origin; the engine scales to Size and rotates around it. BaseAngleDeg is the
direction the fingertip points in this geometry (up).

Run:  python tools/gen-hand-shape.py
"""

from pathlib import Path

import numpy as np
from svgpathtools import svg2paths
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SVG = ROOT / "tools" / "mouse-hand-cursor-icon.svg"
CS_OUT = ROOT / "src" / "WormsCursor.Core" / "HandShape.cs"
PREVIEW = ROOT / "tools" / "_hand-final.png"


def flatten():
    paths, _ = svg2paths(str(SVG))
    subs = []
    for p in paths:
        for sp in p.continuous_subpaths():
            L = sp.length() or 1
            n = max(48, int(L / 0.6))
            subs.append([(sp.point(i / n).real, sp.point(i / n).imag) for i in range(n + 1)])
    return subs


def area(pts):
    a = 0.0
    for i in range(len(pts) - 1):
        a += pts[i][0] * pts[i + 1][1] - pts[i + 1][0] * pts[i][1]
    return abs(a) / 2


def main():
    subs = flatten()
    subs.sort(key=area, reverse=True)
    silhouette = subs[0]        # biggest contour = outer edge of the hand = fill body
    lineart = subs              # ALL contours, drawn even-odd = the full line drawing

    fx, fy = min(silhouette, key=lambda p: p[1])   # hotspot = index fingertip (topmost)

    def shift(pts):
        return [(x - fx, y - fy) for x, y in pts]

    sil = shift(silhouette)
    art = [shift(c) for c in lineart]

    # ---- preview: fill silhouette, then even-odd line-art on top ----
    allpts = [p for c in art for p in c]
    minx = min(x for x, _ in allpts); maxx = max(x for x, _ in allpts)
    miny = min(y for _, y in allpts); maxy = max(y for _, y in allpts)
    w, h = maxx - minx, maxy - miny

    def render(size, fill=(255, 255, 255, 255), line=(0, 0, 0, 255)):
        SS = 4; H = size * SS; W = int(round(H * w / h)); pad = int(H * 0.08); s = (H - 2 * pad) / h
        def tf(p): return ((p[0] - minx) * s + (W - w * s) / 2, (p[1] - miny) * s + pad)
        img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
        ImageDraw.Draw(img).polygon([tf(p) for p in sil], fill=fill)         # solid body
        parity = np.zeros((H, W), bool)                                       # even-odd line-art
        for c in art:
            m = Image.new("1", (W, H), 0); ImageDraw.Draw(m).polygon([tf(p) for p in c], fill=1)
            parity ^= np.array(m, bool)
        a = np.array(img); a[parity] = line; img = Image.fromarray(a, "RGBA")
        return img.resize((max(1, int(W / SS)), int(H / SS)), Image.LANCZOS)

    big = render(220); BW, BH = big.size
    sheet = Image.new("RGBA", (BW + 40 + 4 * 64, BH + 40), (31, 31, 31, 255))
    sheet.alpha_composite(big, (20, 20)); x = BW + 40
    for sz in [16, 24, 32, 48]:
        sheet.alpha_composite(render(sz), (x, 50)); x += 64
    sheet.convert("RGB").save(PREVIEW)

    # ---- emit C# ----
    def fmt(pts):
        return ", ".join(f"{x:.2f}f, {y:.2f}f" for x, y in pts)

    art_arrays = ",\n        ".join("new float[] { " + fmt(c) + " }" for c in art)
    cs = f"""namespace WormsCursor.Core;

// Generated by tools/gen-hand-shape.py from tools/mouse-hand-cursor-icon.svg — do not edit by hand.
// Polylines in reference units, translated so the index fingertip (the hotspot) is at
// the origin. The engine scales to Size and rotates the shape around this point.
internal static class HandShape
{{
    // Direction the fingertip points in this geometry (screen: up = -Y).
    public const double BaseAngleDeg = -90.0;

    // Outer silhouette, filled with FillColor for an opaque body. x,y pairs.
    public static readonly float[] Silhouette =
    {{
        {fmt(sil)}
    }};

    // The full line drawing (outline + finger lines + knuckle marks). Filled even-odd
    // (FillMode.Alternate) in OutlineColor on top of the body.
    public static readonly float[][] LineArt =
    {{
        {art_arrays}
    }};
}}
"""
    CS_OUT.write_text(cs, encoding="utf-8")
    print(f"silhouette pts: {len(sil)}  lineart contours: {len(art)} ({[len(c) for c in art]})")
    print(f"fingertip (hotspot) at svg ({fx:.1f},{fy:.1f})")
    print(f"wrote {CS_OUT} ({CS_OUT.stat().st_size} bytes); wrote {PREVIEW}")


if __name__ == "__main__":
    main()
